---
- name: Install basic dependencies
  tags:
    [
      "basics",
      "git",
      "curl",
      "wget",
      "build-essential",
      "zsh",
      "tmux",
      "ccze",
      "direnv",
      "redshift",
      "xsel",
      "fonts",
      "ncdu",
      "nmon",
      "iotop",
      "iftop",
    ]
  apt:
    name:
      - git
      - curl
      - wget
      - build-essential
      - zsh
      - tmux
      - ccze
      - direnv
      - redshift
      - xsel
      - fonts-ibm-plex
      - ncdu
      - nmon
      - iotop
      - iftop
    state: present
