---
- name: Clone spaceship-prompt repository
  tags: ['spaceship-prompt']
  git:
    repo: 'https://github.com/spaceship-prompt/spaceship-prompt.git'
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    version: "{{ spaceship_prompt_version }}"
    depth: 1
    update: yes
  become: false

- name: Create symlink for spaceship theme
  tags: ['spaceship-prompt']
  file:
    src: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
  become: false
