---
- name: Check if fd is installed
  tags: ['fd']
  stat:
    path: /usr/local/bin/fd
  register: fd_stat

- name: Download and install fd
  tags: ['fd']
  block:
    - name: Create temporary directory for fd
      tempfile:
        state: directory
      register: fd_temp

    - name: Download fd tarball
      get_url:
        url: "https://github.com/sharkdp/fd/releases/download/{{ fd_version }}/fd-{{ fd_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ fd_temp.path }}/fd.tar.gz"

    - name: Extract fd tarball
      unarchive:
        src: "{{ fd_temp.path }}/fd.tar.gz"
        dest: "{{ fd_temp.path }}"
        remote_src: yes

    - name: Find fd binary in extracted directory
      find:
        paths: "{{ fd_temp.path }}"
        patterns: "fd"
        recurse: yes
        file_type: file
      register: fd_binary

    - name: Install fd to /usr/local/bin
      copy:
        src: "{{ fd_binary.files[0].path }}"
        dest: /usr/local/bin/fd
        mode: '0755'
        remote_src: yes

    - name: Clean up fd temporary directory
      file:
        path: "{{ fd_temp.path }}"
        state: absent
  when: not fd_stat.stat.exists or (force_update | default(false) | bool)
